# خواندن فایل با فرمت های مختلف و تبدیل آنها به همدیگر

### وارد کردن کتابخانه های مورد نیاز

In [12]:
import pandas as pd

In [13]:
# read Excel file
pd.read_excel("persons.xlsx")

    name  family  age
0    ali   alavi   23
1   reza   rezai   25
2  excel  office   30

In [14]:
# read csv file
pd.read_csv("persons.csv")

  name,family,age
0    ali,alavi,22
1     text,csv,30

In [16]:
# read json
pd.read_json("persons.json")

   name family  age
0   ali  alavi   23
1  reza  rezai   25
2  json   json   27

In [17]:
# read xml
pd.read_xml("persons.xml")

  name family  age
0  ali  alavi   24
1  xml    xml   28

In [22]:
# Excel to json
data = pd.read_excel("persons.xlsx")
data.to_json("ex_to_json.json",orient = "records")

In [23]:
# json to csv & Excel
data0 = pd.read_json("persons.json")
data0.to_csv("json_to_csv.csv")
data0.to_excel("json_to_excel.xlsx")

In [27]:
# changes in data
data = pd.read_excel("persons.xlsx")
data["life-days"] = data["age"] *365
data.to_csv("ex_to_csv.csv")
data

    name  family  age  life-days
0    ali   alavi   23       8395
1   reza   rezai   25       9125
2  excel  office   30      10950

In [28]:
import sys
print(sys.executable)

C:\Users\feres\AppData\Local\Programs\Python\Python312\python.exe